# 创建 island
sketchybar --add item island center

# 设置脚本
sketchybar --set island \
script="$HOME/.config/sketchybar/island.sh" \
update_freq=5

# 订阅事件（关键）
sketchybar --subscribe island front_app_switched
